/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.kelompok1.kocokarisan.view;

/**
 *
 * @author HLDN
 */
public class loginPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public loginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        fieldUsername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        fieldPassword = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        buttonLogin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labelRegister = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labelMinimize = new javax.swing.JLabel();
        labelClose = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(767, 468));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setBackground(new java.awt.Color(25, 16, 9));
        panelLogin.setPreferredSize(new java.awt.Dimension(767, 468));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 162, 92));
        jLabel1.setText("LOGO");
        panelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 73, 61));

        labelUsername.setBackground(new java.awt.Color(239, 162, 92));
        labelUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(239, 162, 92));
        labelUsername.setText("USERNAME");
        panelLogin.add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 109, -1));

        labelPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(239, 162, 92));
        labelPassword.setText("PASSWORD");
        panelLogin.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 70, 22));

        fieldUsername.setBackground(new java.awt.Color(25, 16, 9));
        fieldUsername.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        fieldUsername.setForeground(new java.awt.Color(133, 136, 107));
        fieldUsername.setText("HULDAN");
        fieldUsername.setBorder(null);
        fieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUsernameActionPerformed(evt);
            }
        });
        panelLogin.add(fieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 141, -1));

        jSeparator1.setBackground(new java.awt.Color(133, 136, 107));
        jSeparator1.setForeground(new java.awt.Color(133, 136, 107));
        panelLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 170, 10));

        fieldPassword.setBackground(new java.awt.Color(25, 16, 9));
        fieldPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        fieldPassword.setForeground(new java.awt.Color(133, 136, 107));
        fieldPassword.setText("jPasswordField1");
        fieldPassword.setBorder(null);
        panelLogin.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 140, -1));

        jSeparator3.setBackground(new java.awt.Color(133, 136, 107));
        jSeparator3.setForeground(new java.awt.Color(133, 136, 107));
        panelLogin.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 170, 10));

        buttonLogin.setBackground(new java.awt.Color(239, 162, 92));
        buttonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLoginMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 16, 9));
        jLabel4.setText("LOGIN");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout buttonLoginLayout = new javax.swing.GroupLayout(buttonLogin);
        buttonLogin.setLayout(buttonLoginLayout);
        buttonLoginLayout.setHorizontalGroup(
            buttonLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonLoginLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        buttonLoginLayout.setVerticalGroup(
            buttonLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        panelLogin.add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        labelRegister.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        labelRegister.setForeground(new java.awt.Color(133, 136, 107));
        labelRegister.setText("Belum mendaftar? daftar disini");
        panelLogin.add(labelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 144, 22));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\HLDN\\Downloads\\user-shape.png")); // NOI18N
        panelLogin.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\HLDN\\Downloads\\key-silhouette-security-tool-interface-symbol-of-password.png")); // NOI18N
        panelLogin.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        labelMinimize.setIcon(new javax.swing.ImageIcon("C:\\Users\\HLDN\\Downloads\\minimize-tab.png")); // NOI18N
        labelMinimize.setText("jLabel6");
        panelLogin.add(labelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 20, 20));

        labelClose.setIcon(new javax.swing.ImageIcon("C:\\Users\\HLDN\\Downloads\\error.png")); // NOI18N
        labelClose.setText("jLabel6");
        panelLogin.add(labelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 20, 20));

        add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUsernameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_fieldUsernameActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        menuPanel n = new menuPanel();
        n.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void buttonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLoginMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonLogin;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelClose;
    private javax.swing.JLabel labelMinimize;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelRegister;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel panelLogin;
    // End of variables declaration//GEN-END:variables

}
