/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.kelompok1.kocokarisan.view;

import ClassAnimation.sSlide;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
/**
 *
 * @author HLDN
 */
public class menuFrame extends javax.swing.JFrame {

    /**
     * Creates new form menuFrame
     */
    sSlide slide;
    public menuFrame() {
        initComponents();
        slide = new sSlide();
    }
    public void PanelKeKiri(){
        slide.jPanelXKiri(0, -180, 7, 5, menuPanel);
    }
    public void PanelKeKanan(){
        slide.jPanelXKanan(-180, 0, 7, 5, menuPanel);
    }

    public JTextField getTxtEmailMenuFrame() {
        return txtEmailMenuFrame;
    }

    public void setTxtEmailMenuFrame(JTextField txtEmailMenuFrame) {
        this.txtEmailMenuFrame = txtEmailMenuFrame;
    }

    public JPasswordField getTxtPasswordMenuFrame() {
        return txtPasswordMenuFrame;
    }

    public void setTxtPasswordMenuFrame(JPasswordField txtPasswordMenuFrame) {
        this.txtPasswordMenuFrame = txtPasswordMenuFrame;
    }

    public JTextField getTxtUsernameMenuFrame() {
        return txtUsernameMenuFrame;
    }

    public void setTxtUsernameMenuFrame(JTextField txtUsernameMenuFrame) {
        this.txtUsernameMenuFrame = txtUsernameMenuFrame;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jLabelHome = new javax.swing.JLabel();
        jLabelAbout = new javax.swing.JLabel();
        jLabelSett = new javax.swing.JLabel();
        jLabelKelArs = new javax.swing.JLabel();
        buttonLogOut = new javax.swing.JLabel();
        labelAdmin = new javax.swing.JLabel();
        buttonMenu = new javax.swing.JLabel();
        buttonKelompok = new javax.swing.JLabel();
        buttonAbout = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        buttonSetting = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel49 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        buttonHome1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        panelUtama = new javax.swing.JPanel();
        labelAngka = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        labelMinimizeUtama = new javax.swing.JLabel();
        labelCloseUtama = new javax.swing.JLabel();
        kelompokPanel = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        settingPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtEmailMenuFrame = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtUsernameMenuFrame = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPasswordMenuFrame = new javax.swing.JPasswordField();
        labelSetting = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        aboutPanelFix = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelSetting7 = new javax.swing.JLabel();
        labelSetting8 = new javax.swing.JLabel();
        labelSetting9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 162, 92), 2));
        panelMain.setPreferredSize(new java.awt.Dimension(767, 468));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(236, 245, 192));
        menuPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuPanel.setPreferredSize(new java.awt.Dimension(240, 468));
        menuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPanelMouseExited(evt);
            }
        });
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
        });
        menuPanel.add(jLabelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 50));

        jLabelAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAboutMouseClicked(evt);
            }
        });
        menuPanel.add(jLabelAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 50));

        jLabelSett.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSett.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSettMouseClicked(evt);
            }
        });
        menuPanel.add(jLabelSett, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, 50));

        jLabelKelArs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelKelArs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelKelArsMouseClicked(evt);
            }
        });
        menuPanel.add(jLabelKelArs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 50));

        buttonLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/logout.png"))); // NOI18N
        buttonLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLogOutMouseClicked(evt);
            }
        });
        menuPanel.add(buttonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        labelAdmin.setBackground(new java.awt.Color(239, 162, 92));
        labelAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelAdmin.setForeground(new java.awt.Color(239, 162, 92));
        labelAdmin.setText("admin");
        menuPanel.add(labelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 80, 30));

        buttonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/MENU.png"))); // NOI18N
        buttonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMenuMouseClicked(evt);
            }
        });
        menuPanel.add(buttonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 30, 40));

        buttonKelompok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/KELOMPOK.png"))); // NOI18N
        buttonKelompok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonKelompokMouseClicked(evt);
            }
        });
        menuPanel.add(buttonKelompok, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 30, 30));

        buttonAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/ABOUT.png"))); // NOI18N
        menuPanel.add(buttonAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 30, 40));

        jLabel23.setBackground(new java.awt.Color(239, 162, 92));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(25, 16, 9));
        jLabel23.setText("About");
        menuPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 60, 30));

        jLabel24.setBackground(new java.awt.Color(239, 162, 92));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(239, 162, 92));
        jLabel24.setText("Hallo");
        menuPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 50, 30));

        jLabel25.setBackground(new java.awt.Color(25, 16, 9));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(25, 16, 9));
        jLabel25.setText("Home");
        menuPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 30));

        jSeparator6.setBackground(new java.awt.Color(239, 162, 92));
        jSeparator6.setForeground(new java.awt.Color(239, 162, 92));
        menuPanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, 10));

        jSeparator7.setBackground(new java.awt.Color(239, 162, 92));
        jSeparator7.setForeground(new java.awt.Color(239, 162, 92));
        menuPanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, 10));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/ADMIN.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        menuPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 30, 30));

        buttonSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/SETTING.png"))); // NOI18N
        menuPanel.add(buttonSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 30, 40));

        jLabel32.setBackground(new java.awt.Color(239, 162, 92));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(25, 16, 9));
        jLabel32.setText("Setting");
        menuPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 60, 30));

        jSeparator9.setBackground(new java.awt.Color(239, 162, 92));
        jSeparator9.setForeground(new java.awt.Color(239, 162, 92));
        menuPanel.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, 10));

        jLabel49.setBackground(new java.awt.Color(25, 16, 9));
        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(25, 16, 9));
        jLabel49.setText("Kelompok Arisan");
        menuPanel.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        jSeparator10.setBackground(new java.awt.Color(239, 162, 92));
        jSeparator10.setForeground(new java.awt.Color(239, 162, 92));
        menuPanel.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 10));

        buttonHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/homefix.png"))); // NOI18N
        menuPanel.add(buttonHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        panelMain.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, -1, -1));

        mainPanel.setPreferredSize(new java.awt.Dimension(767, 468));
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainPanelMouseEntered(evt);
            }
        });
        mainPanel.setLayout(new java.awt.CardLayout());

        panelUtama.setBackground(new java.awt.Color(25, 16, 9));
        panelUtama.setMinimumSize(new java.awt.Dimension(767, 468));
        panelUtama.setPreferredSize(new java.awt.Dimension(767, 468));
        panelUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAngka.setBackground(new java.awt.Color(239, 162, 92));
        labelAngka.setFont(new java.awt.Font("Segoe UI Semibold", 0, 120)); // NOI18N
        labelAngka.setForeground(new java.awt.Color(236, 245, 192));
        labelAngka.setText("2");
        panelUtama.add(labelAngka, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 172, -1));

        jLabel27.setBackground(new java.awt.Color(239, 162, 92));
        jLabel27.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(239, 162, 92));
        jLabel27.setText("Kelompok Arisan");
        panelUtama.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 380, 73));

        jLabel28.setBackground(new java.awt.Color(239, 162, 92));
        jLabel28.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(239, 162, 92));
        jLabel28.setText("saat ini ada");
        panelUtama.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 276, 54));

        jSeparator8.setBackground(new java.awt.Color(236, 245, 192));
        jSeparator8.setForeground(new java.awt.Color(236, 245, 192));
        panelUtama.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 490, 20));

        labelMinimizeUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/MINIMIZE.png"))); // NOI18N
        labelMinimizeUtama.setText("jLabel6");
        labelMinimizeUtama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelMinimizeUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizeUtamaMouseClicked(evt);
            }
        });
        panelUtama.add(labelMinimizeUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 20, 20));

        labelCloseUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/CLOSE.png"))); // NOI18N
        labelCloseUtama.setText("jLabel6");
        labelCloseUtama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCloseUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCloseUtamaMouseClicked(evt);
            }
        });
        panelUtama.add(labelCloseUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 20, 20));

        mainPanel.add(panelUtama, "card2");

        kelompokPanel.setBackground(new java.awt.Color(25, 16, 9));
        kelompokPanel.setMinimumSize(new java.awt.Dimension(767, 468));
        kelompokPanel.setPreferredSize(new java.awt.Dimension(710, 468));
        kelompokPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(239, 162, 92));
        jLabel26.setText("Kelompok Arisan");
        kelompokPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 268, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        kelompokPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 540, 163));

        jPanel7.setBackground(new java.awt.Color(236, 245, 192));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(25, 16, 9));
        jLabel29.setText("TAMPIL");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel29)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        kelompokPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 90, 30));

        jPanel8.setBackground(new java.awt.Color(239, 162, 92));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(25, 16, 9));
        jLabel30.setText("Tambah");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(23, 23, 23))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        kelompokPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 90, 30));

        jPanel9.setBackground(new java.awt.Color(239, 162, 92));
        jPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel9MouseDragged(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(25, 16, 9));
        jLabel31.setText("Ubah");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel31)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        kelompokPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 90, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/CLOSE.png"))); // NOI18N
        jLabel13.setText("jLabel6");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        kelompokPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 20, 20));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/MINIMIZE.png"))); // NOI18N
        jLabel21.setText("jLabel6");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        kelompokPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 20, 20));

        mainPanel.add(kelompokPanel, "card3");

        settingPanel.setBackground(new java.awt.Color(25, 16, 9));
        settingPanel.setPreferredSize(new java.awt.Dimension(767, 468));

        jLabel10.setBackground(new java.awt.Color(239, 162, 92));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(239, 162, 92));
        jLabel10.setText("EMAIL :");

        txtEmailMenuFrame.setBackground(new java.awt.Color(133, 136, 107));
        txtEmailMenuFrame.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtEmailMenuFrame.setForeground(new java.awt.Color(25, 16, 9));
        txtEmailMenuFrame.setBorder(null);

        jLabel11.setBackground(new java.awt.Color(239, 162, 92));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(239, 162, 92));
        jLabel11.setText("USERNAME :");

        txtUsernameMenuFrame.setBackground(new java.awt.Color(133, 136, 107));
        txtUsernameMenuFrame.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtUsernameMenuFrame.setForeground(new java.awt.Color(25, 16, 9));
        txtUsernameMenuFrame.setBorder(null);

        jLabel12.setBackground(new java.awt.Color(239, 162, 92));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(239, 162, 92));
        jLabel12.setText("PASSWORD :");

        txtPasswordMenuFrame.setBackground(new java.awt.Color(133, 136, 107));
        txtPasswordMenuFrame.setForeground(new java.awt.Color(25, 16, 9));
        txtPasswordMenuFrame.setBorder(null);

        labelSetting.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        labelSetting.setForeground(new java.awt.Color(239, 162, 92));
        labelSetting.setText("Setting");

        jPanel10.setBackground(new java.awt.Color(239, 162, 92));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(25, 16, 9));
        jLabel34.setText("Ubah");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(236, 245, 192));
        jPanel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(25, 16, 9));
        jLabel35.setText("Reset");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(239, 162, 92));
        jPanel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(25, 16, 9));
        jLabel36.setText("Hapus");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jLabel33.setText("jLabel6");

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/CLOSE.png"))); // NOI18N
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/MINIMIZE.png"))); // NOI18N
        jLabel41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingPanelLayout.createSequentialGroup()
                        .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(settingPanelLayout.createSequentialGroup()
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtUsernameMenuFrame, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSetting, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmailMenuFrame, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPasswordMenuFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel40)
                        .addContainerGap())))
            .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(settingPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel33)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41))
                .addGap(33, 33, 33)
                .addComponent(labelSetting)
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailMenuFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsernameMenuFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPasswordMenuFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(settingPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel33)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainPanel.add(settingPanel, "card4");

        aboutPanelFix.setBackground(new java.awt.Color(25, 16, 9));
        aboutPanelFix.setPreferredSize(new java.awt.Dimension(767, 468));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/MINIMIZE.png"))); // NOI18N
        jLabel42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/CLOSE.png"))); // NOI18N
        jLabel43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/logo.png"))); // NOI18N

        labelSetting7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelSetting7.setForeground(new java.awt.Color(239, 162, 92));
        labelSetting7.setText("Aplikasi Kocok Arisan");

        labelSetting8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelSetting8.setForeground(new java.awt.Color(239, 162, 92));
        labelSetting8.setText("version 3.3.0");

        labelSetting9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelSetting9.setForeground(new java.awt.Color(239, 162, 92));
        labelSetting9.setText("develoved By : Kelompok 1");

        javax.swing.GroupLayout aboutPanelFixLayout = new javax.swing.GroupLayout(aboutPanelFix);
        aboutPanelFix.setLayout(aboutPanelFixLayout);
        aboutPanelFixLayout.setHorizontalGroup(
            aboutPanelFixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelFixLayout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addGroup(aboutPanelFixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelFixLayout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel43)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelFixLayout.createSequentialGroup()
                        .addGroup(aboutPanelFixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aboutPanelFixLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel2)
                                .addGap(163, 163, 163))
                            .addComponent(labelSetting7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelFixLayout.createSequentialGroup()
                                .addComponent(labelSetting8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelFixLayout.createSequentialGroup()
                                .addComponent(labelSetting9, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)))
                        .addGap(152, 152, 152))))
        );
        aboutPanelFixLayout.setVerticalGroup(
            aboutPanelFixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelFixLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutPanelFixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43))
                .addGap(120, 120, 120)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(labelSetting7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSetting8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSetting9)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        mainPanel.add(aboutPanelFix, "card5");

        panelMain.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 0, 710, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKelompokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonKelompokMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonKelompokMouseClicked

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        // TODO add your handling code here:
        
        PanelKeKiri();
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(panelUtama);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabelHomeMouseClicked

    private void jLabelSettMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSettMouseClicked
        // TODO add your handling code here:
        PanelKeKiri();
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(settingPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_jLabelSettMouseClicked

    private void jLabelAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAboutMouseClicked
        // TODO add your handling code here:
        PanelKeKiri();
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(aboutPanelFix);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabelAboutMouseClicked

    private void jLabelKelArsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelKelArsMouseClicked
        // TODO add your handling code here:
        PanelKeKiri();
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(kelompokPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabelKelArsMouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        popUpFrameTambah n  = new popUpFrameTambah();
        n.setVisible(true);
       
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseDragged
        // TODO add your handling code here:
        popUpFrameUbah n  = new popUpFrameUbah();
        n.setVisible(true);

    }//GEN-LAST:event_jPanel9MouseDragged

    private void menuPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanelMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuPanelMouseExited

    private void mainPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseEntered
        // TODO add your handling code here:
        PanelKeKiri();
    }//GEN-LAST:event_mainPanelMouseEntered

    private void buttonLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLogOutMouseClicked
        // TODO add your handling code here:
        logouFrame n = new logouFrame();
        n.setVisible(true);
    }//GEN-LAST:event_buttonLogOutMouseClicked

    private void labelCloseUtamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCloseUtamaMouseClicked
        // TODO add your handling code here:
        dialogFrame n  = new dialogFrame();
        n.setVisible(true);
    }//GEN-LAST:event_labelCloseUtamaMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        dialogFrame n  = new dialogFrame();
        n.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        // TODO add your handling code here:
        dialogFrame n  = new dialogFrame();
        n.setVisible(true);
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
        // TODO add your handling code here:
        dialogFrame n  = new dialogFrame();
        n.setVisible(true);
    }//GEN-LAST:event_jLabel43MouseClicked

    private void labelMinimizeUtamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeUtamaMouseClicked
        // TODO add your handling code here:
        this.setState(menuFrame.ICONIFIED);
    }//GEN-LAST:event_labelMinimizeUtamaMouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        this.setState(menuFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        // TODO add your handling code here:
        this.setState(menuFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        // TODO add your handling code here:
        this.setState(menuFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel42MouseClicked

    private void buttonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMenuMouseClicked
        // TODO add your handling code here:
        PanelKeKanan();
        PanelKeKiri();
    }//GEN-LAST:event_buttonMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanelFix;
    private javax.swing.JLabel buttonAbout;
    private javax.swing.JLabel buttonHome1;
    private javax.swing.JLabel buttonKelompok;
    private javax.swing.JLabel buttonLogOut;
    private javax.swing.JLabel buttonMenu;
    private javax.swing.JLabel buttonSetting;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabelAbout;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelKelArs;
    private javax.swing.JLabel jLabelSett;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel kelompokPanel;
    private javax.swing.JLabel labelAdmin;
    private javax.swing.JLabel labelAngka;
    private javax.swing.JLabel labelCloseUtama;
    private javax.swing.JLabel labelMinimizeUtama;
    private javax.swing.JLabel labelSetting;
    private javax.swing.JLabel labelSetting7;
    private javax.swing.JLabel labelSetting8;
    private javax.swing.JLabel labelSetting9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JPanel settingPanel;
    private javax.swing.JTextField txtEmailMenuFrame;
    private javax.swing.JPasswordField txtPasswordMenuFrame;
    private javax.swing.JTextField txtUsernameMenuFrame;
    // End of variables declaration//GEN-END:variables
}