/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.kelompok1.kocokarisan.view;

import ClassAnimation.sSlide;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
/**
 *
 * @author HLDN
 */
public class menuFrame extends javax.swing.JFrame {

    /**
     * Creates new form menuFrame
     */
    sSlide slide;
    public menuFrame() {
        initComponents();
        slide = new sSlide();
    }
    public void PanelKeKiri(){
        slide.jPanelXKiri(0, -180, 7, 5, menuPanel);
    }
    public void PanelKeKanan(){
        slide.jPanelXKanan(-180, 0, 7, 5, menuPanel);
    }

    public JTextField getTxtEmailMenuFrame() {
        return txtEmail;
    }

    public void setTxtEmailMenuFrame(JTextField txtEmailMenuFrame) {
        this.txtEmail = txtEmailMenuFrame;
    }

    public JPasswordField getTxtPasswordMenuFrame() {
        return txtPasswordMenuFrame;
    }

    public void setTxtPasswordMenuFrame(JPasswordField txtPasswordMenuFrame) {
        this.txtPasswordMenuFrame = txtPasswordMenuFrame;
    }

    public JTextField getTxtUsernameMenuFrame() {
        return txtUsernameSetting;
    }

    public void setTxtUsernameMenuFrame(JTextField txtUsernameMenuFrame) {
        this.txtUsernameSetting = txtUsernameMenuFrame;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMinimaselogoTabbahAnngota1 = new javax.swing.JLabel();
        lblExitTambbahAnggota1 = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblAbout = new javax.swing.JLabel();
        lblSetting = new javax.swing.JLabel();
        lblKelompok = new javax.swing.JLabel();
        buttonLogOut = new javax.swing.JLabel();
        labelAdmin = new javax.swing.JLabel();
        btnMenu = new javax.swing.JLabel();
        buttonKelompok = new javax.swing.JLabel();
        buttonAbout = new javax.swing.JLabel();
        lblAboutText = new javax.swing.JLabel();
        lblHalloText = new javax.swing.JLabel();
        lblHomeText = new javax.swing.JLabel();
        seperatorAbout = new javax.swing.JSeparator();
        separatorHome = new javax.swing.JSeparator();
        lblLogoAdmin = new javax.swing.JLabel();
        buttonSetting = new javax.swing.JLabel();
        lblSettingtext = new javax.swing.JLabel();
        separatorSetting = new javax.swing.JSeparator();
        lblKelompokText = new javax.swing.JLabel();
        separatorKelompok = new javax.swing.JSeparator();
        buttonHome1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        panelUtama = new javax.swing.JPanel();
        labelAngka = new javax.swing.JLabel();
        lblHomeKelompok = new javax.swing.JLabel();
        lblDuaHome = new javax.swing.JLabel();
        separatorPanelUtama = new javax.swing.JSeparator();
        labelMinimizeUtama = new javax.swing.JLabel();
        labelCloseUtama = new javax.swing.JLabel();
        kelompokPanel = new javax.swing.JPanel();
        tabel = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnTampil = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        btnResetKelompok = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        closeKelompokPanel = new javax.swing.JLabel();
        minimizeKelompokPanel = new javax.swing.JLabel();
        lblAnggota1 = new javax.swing.JLabel();
        lblJumlah1 = new javax.swing.JLabel();
        lblJadwal1 = new javax.swing.JLabel();
        txtJumlahSetoranklmpk = new javax.swing.JFormattedTextField();
        txtJumlahAnggotaklmpok = new javax.swing.JTextField();
        txtIdKelompok = new javax.swing.JTextField();
        combo3 = new javax.swing.JComboBox<>();
        combo4 = new javax.swing.JComboBox<>();
        lblNamagrup1 = new javax.swing.JLabel();
        btnUbahklmpok = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        btnHapusklmpok = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        lblNamagrup2 = new javax.swing.JLabel();
        txtNameKelompok = new javax.swing.JTextField();
        lblNamagrup3 = new javax.swing.JLabel();
        settingPanel = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsernameSetting = new javax.swing.JTextField();
        lblPasswordSetting = new javax.swing.JLabel();
        txtPasswordMenuFrame = new javax.swing.JPasswordField();
        labelSetting = new javax.swing.JLabel();
        btnUbahSetting = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        btnResetSetting = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        btnHapusSetting = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        btnCloseSet = new javax.swing.JLabel();
        btnMiniizeSet = new javax.swing.JLabel();
        aboutPanelFix = new javax.swing.JPanel();
        lblMinimizeAbout = new javax.swing.JLabel();
        lblCloseAbout = new javax.swing.JLabel();
        lblLogoAbout = new javax.swing.JLabel();
        lblAboutNama = new javax.swing.JLabel();
        lblAboutVersi = new javax.swing.JLabel();
        lblAboutDeveloped = new javax.swing.JLabel();
        tambahAnggotaPanel1 = new javax.swing.JPanel();
        labelSetting10 = new javax.swing.JLabel();
        btnUbahAnggota = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        btnResetTambahAnngota = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        btnHapusAnggota = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        lblMinimaselogoTabbahAnngota = new javax.swing.JLabel();
        lblExitTambbahAnggota = new javax.swing.JLabel();
        lblIdanggotaTabahAnggota = new javax.swing.JLabel();
        lblNamaanggotaUbah = new javax.swing.JLabel();
        lblAlamatTambahAnggota = new javax.swing.JLabel();
        lblIkutarisanTambahAnggota = new javax.swing.JLabel();
        txtIdanggota = new javax.swing.JTextField();
        txtNamaanggota = new javax.swing.JTextField();
        txtAlamatTambahAnggota = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        listIkutarisanTambahAnggota = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTambahanggotaTambbahAnggota = new javax.swing.JTable();
        lblMulaiTambahAnggita = new javax.swing.JLabel();
        btnTambahAnggota = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        tampilPanel = new javax.swing.JPanel();
        btnTampilPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tabel1 = new javax.swing.JScrollPane();
        tabelTampil = new javax.swing.JTable();
        lblMinimalieTmpilKelompok = new javax.swing.JLabel();
        lblExitTampilK = new javax.swing.JLabel();
        lblNamagrup4 = new javax.swing.JLabel();

        lblMinimaselogoTabbahAnngota1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/MINIMIZE.png"))); // NOI18N
        lblMinimaselogoTabbahAnngota1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimaselogoTabbahAnngota1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimaselogoTabbahAnngota1MouseClicked(evt);
            }
        });

        lblExitTambbahAnggota1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/CLOSE.png"))); // NOI18N
        lblExitTambbahAnggota1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExitTambbahAnggota1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitTambbahAnggota1MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 162, 92), 2));
        panelMain.setPreferredSize(new java.awt.Dimension(767, 468));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(236, 245, 192));
        menuPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuPanel.setPreferredSize(new java.awt.Dimension(240, 468));
        menuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPanelMouseExited(evt);
            }
        });
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        menuPanel.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 50));

        lblAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAboutMouseClicked(evt);
            }
        });
        menuPanel.add(lblAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 50));

        lblSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSettingMouseClicked(evt);
            }
        });
        menuPanel.add(lblSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, 50));

        lblKelompok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKelompok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKelompokMouseClicked(evt);
            }
        });
        menuPanel.add(lblKelompok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 50));

        buttonLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/logout.png"))); // NOI18N
        buttonLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLogOutMouseClicked(evt);
            }
        });
        menuPanel.add(buttonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        labelAdmin.setBackground(new java.awt.Color(239, 162, 92));
        labelAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelAdmin.setForeground(new java.awt.Color(239, 162, 92));
        labelAdmin.setText("admin");
        menuPanel.add(labelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 80, 30));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/MENU.png"))); // NOI18N
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        menuPanel.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 30, 40));

        buttonKelompok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/KELOMPOK.png"))); // NOI18N
        buttonKelompok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonKelompokMouseClicked(evt);
            }
        });
        menuPanel.add(buttonKelompok, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 30, 30));

        buttonAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/ABOUT.png"))); // NOI18N
        menuPanel.add(buttonAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 30, 40));

        lblAboutText.setBackground(new java.awt.Color(239, 162, 92));
        lblAboutText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAboutText.setForeground(new java.awt.Color(25, 16, 9));
        lblAboutText.setText("About");
        menuPanel.add(lblAboutText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 60, 30));

        lblHalloText.setBackground(new java.awt.Color(239, 162, 92));
        lblHalloText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHalloText.setForeground(new java.awt.Color(239, 162, 92));
        lblHalloText.setText("Hallo");
        menuPanel.add(lblHalloText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 50, 30));

        lblHomeText.setBackground(new java.awt.Color(25, 16, 9));
        lblHomeText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHomeText.setForeground(new java.awt.Color(25, 16, 9));
        lblHomeText.setText("Home");
        menuPanel.add(lblHomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 30));

        seperatorAbout.setBackground(new java.awt.Color(239, 162, 92));
        seperatorAbout.setForeground(new java.awt.Color(239, 162, 92));
        menuPanel.add(seperatorAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, 10));

        separatorHome.setBackground(new java.awt.Color(239, 162, 92));
        separatorHome.setForeground(new java.awt.Color(239, 162, 92));
        menuPanel.add(separatorHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, 10));

        lblLogoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/ADMIN.png"))); // NOI18N
        lblLogoAdmin.setText("jLabel14");
        menuPanel.add(lblLogoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 30, 30));

        buttonSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/SETTING.png"))); // NOI18N
        menuPanel.add(buttonSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 30, 40));

        lblSettingtext.setBackground(new java.awt.Color(239, 162, 92));
        lblSettingtext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSettingtext.setForeground(new java.awt.Color(25, 16, 9));
        lblSettingtext.setText("Setting");
        menuPanel.add(lblSettingtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 60, 30));

        separatorSetting.setBackground(new java.awt.Color(239, 162, 92));
        separatorSetting.setForeground(new java.awt.Color(239, 162, 92));
        menuPanel.add(separatorSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, 10));

        lblKelompokText.setBackground(new java.awt.Color(25, 16, 9));
        lblKelompokText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKelompokText.setForeground(new java.awt.Color(25, 16, 9));
        lblKelompokText.setText("Kelompok Arisan");
        menuPanel.add(lblKelompokText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        separatorKelompok.setBackground(new java.awt.Color(239, 162, 92));
        separatorKelompok.setForeground(new java.awt.Color(239, 162, 92));
        menuPanel.add(separatorKelompok, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 10));

        buttonHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/homefix.png"))); // NOI18N
        menuPanel.add(buttonHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        panelMain.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, -1, -1));

        mainPanel.setPreferredSize(new java.awt.Dimension(767, 468));
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainPanelMouseEntered(evt);
            }
        });
        mainPanel.setLayout(new java.awt.CardLayout());

        panelUtama.setBackground(new java.awt.Color(25, 16, 9));
        panelUtama.setMinimumSize(new java.awt.Dimension(767, 468));
        panelUtama.setPreferredSize(new java.awt.Dimension(767, 468));
        panelUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAngka.setBackground(new java.awt.Color(239, 162, 92));
        labelAngka.setFont(new java.awt.Font("Segoe UI Semibold", 0, 120)); // NOI18N
        labelAngka.setForeground(new java.awt.Color(236, 245, 192));
        labelAngka.setText("2");
        panelUtama.add(labelAngka, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 172, -1));

        lblHomeKelompok.setBackground(new java.awt.Color(239, 162, 92));
        lblHomeKelompok.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        lblHomeKelompok.setForeground(new java.awt.Color(239, 162, 92));
        lblHomeKelompok.setText("Kelompok Arisan");
        panelUtama.add(lblHomeKelompok, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 380, 73));

        lblDuaHome.setBackground(new java.awt.Color(239, 162, 92));
        lblDuaHome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        lblDuaHome.setForeground(new java.awt.Color(239, 162, 92));
        lblDuaHome.setText("saat ini ada");
        panelUtama.add(lblDuaHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 276, 54));

        separatorPanelUtama.setBackground(new java.awt.Color(236, 245, 192));
        separatorPanelUtama.setForeground(new java.awt.Color(236, 245, 192));
        panelUtama.add(separatorPanelUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 490, 20));

        labelMinimizeUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/MINIMIZE.png"))); // NOI18N
        labelMinimizeUtama.setText("jLabel6");
        labelMinimizeUtama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelMinimizeUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizeUtamaMouseClicked(evt);
            }
        });
        panelUtama.add(labelMinimizeUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 20, 20));

        labelCloseUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/CLOSE.png"))); // NOI18N
        labelCloseUtama.setText("jLabel6");
        labelCloseUtama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCloseUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCloseUtamaMouseClicked(evt);
            }
        });
        panelUtama.add(labelCloseUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 20, 20));

        mainPanel.add(panelUtama, "card2");

        kelompokPanel.setBackground(new java.awt.Color(25, 16, 9));
        kelompokPanel.setMinimumSize(new java.awt.Dimension(767, 468));
        kelompokPanel.setPreferredSize(new java.awt.Dimension(710, 468));
        kelompokPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.setViewportView(jTable1);

        kelompokPanel.add(tabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 540, 90));

        btnTampil.setBackground(new java.awt.Color(236, 245, 192));
        btnTampil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTampil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTampilMouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(25, 16, 9));
        jLabel29.setText("TAMPIL");

        javax.swing.GroupLayout btnTampilLayout = new javax.swing.GroupLayout(btnTampil);
        btnTampil.setLayout(btnTampilLayout);
        btnTampilLayout.setHorizontalGroup(
            btnTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTampilLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnTampilLayout.setVerticalGroup(
            btnTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        kelompokPanel.add(btnTampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 90, 30));

        btnTambah.setBackground(new java.awt.Color(239, 162, 92));
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(25, 16, 9));
        jLabel30.setText("Tambah");

        javax.swing.GroupLayout btnTambahLayout = new javax.swing.GroupLayout(btnTambah);
        btnTambah.setLayout(btnTambahLayout);
        btnTambahLayout.setHorizontalGroup(
            btnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTambahLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(23, 23, 23))
        );
        btnTambahLayout.setVerticalGroup(
            btnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        kelompokPanel.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 90, 30));

        btnResetKelompok.setBackground(new java.awt.Color(239, 162, 92));
        btnResetKelompok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetKelompok.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnResetKelompokMouseDragged(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(25, 16, 9));
        jLabel31.setText("Reset");

        javax.swing.GroupLayout btnResetKelompokLayout = new javax.swing.GroupLayout(btnResetKelompok);
        btnResetKelompok.setLayout(btnResetKelompokLayout);
        btnResetKelompokLayout.setHorizontalGroup(
            btnResetKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnResetKelompokLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnResetKelompokLayout.setVerticalGroup(
            btnResetKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        kelompokPanel.add(btnResetKelompok, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 90, 30));

        closeKelompokPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/CLOSE.png"))); // NOI18N
        closeKelompokPanel.setText("jLabel6");
        closeKelompokPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeKelompokPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeKelompokPanelMouseClicked(evt);
            }
        });
        kelompokPanel.add(closeKelompokPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 20, 20));

        minimizeKelompokPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/MINIMIZE.png"))); // NOI18N
        minimizeKelompokPanel.setText("jLabel6");
        minimizeKelompokPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeKelompokPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeKelompokPanelMouseClicked(evt);
            }
        });
        kelompokPanel.add(minimizeKelompokPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 20, 20));

        lblAnggota1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblAnggota1.setForeground(new java.awt.Color(239, 162, 92));
        lblAnggota1.setText("Jumlah Anggota");
        kelompokPanel.add(lblAnggota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        lblJumlah1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblJumlah1.setForeground(new java.awt.Color(239, 162, 92));
        lblJumlah1.setText("Jumlah Setoran");
        kelompokPanel.add(lblJumlah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        lblJadwal1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblJadwal1.setForeground(new java.awt.Color(239, 162, 92));
        lblJadwal1.setText("Jadwal");
        kelompokPanel.add(lblJadwal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        txtJumlahSetoranklmpk.setBackground(new java.awt.Color(239, 162, 92));
        txtJumlahSetoranklmpk.setBorder(null);
        txtJumlahSetoranklmpk.setForeground(new java.awt.Color(25, 16, 9));
        try {
            txtJumlahSetoranklmpk.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("Rp. ###,###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        kelompokPanel.add(txtJumlahSetoranklmpk, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 130, 20));

        txtJumlahAnggotaklmpok.setBackground(new java.awt.Color(239, 162, 92));
        txtJumlahAnggotaklmpok.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtJumlahAnggotaklmpok.setForeground(new java.awt.Color(25, 16, 9));
        txtJumlahAnggotaklmpok.setBorder(null);
        txtJumlahAnggotaklmpok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahAnggotaklmpokActionPerformed(evt);
            }
        });
        kelompokPanel.add(txtJumlahAnggotaklmpok, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 130, 20));

        txtIdKelompok.setEditable(false);
        txtIdKelompok.setBackground(new java.awt.Color(239, 162, 92));
        txtIdKelompok.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtIdKelompok.setForeground(new java.awt.Color(25, 16, 9));
        txtIdKelompok.setBorder(null);
        kelompokPanel.add(txtIdKelompok, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 130, 20));

        combo3.setBackground(new java.awt.Color(239, 162, 92));
        combo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        kelompokPanel.add(combo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        combo4.setBackground(new java.awt.Color(239, 162, 92));
        combo4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        combo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        kelompokPanel.add(combo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 60, -1));

        lblNamagrup1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNamagrup1.setForeground(new java.awt.Color(239, 162, 92));
        lblNamagrup1.setText("Kelompok Arisan");
        kelompokPanel.add(lblNamagrup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 210, 30));

        btnUbahklmpok.setBackground(new java.awt.Color(239, 162, 92));
        btnUbahklmpok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUbahklmpok.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnUbahklmpokMouseDragged(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(25, 16, 9));
        jLabel32.setText("Ubah");

        javax.swing.GroupLayout btnUbahklmpokLayout = new javax.swing.GroupLayout(btnUbahklmpok);
        btnUbahklmpok.setLayout(btnUbahklmpokLayout);
        btnUbahklmpokLayout.setHorizontalGroup(
            btnUbahklmpokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUbahklmpokLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnUbahklmpokLayout.setVerticalGroup(
            btnUbahklmpokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        kelompokPanel.add(btnUbahklmpok, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 90, 30));

        btnHapusklmpok.setBackground(new java.awt.Color(239, 162, 92));
        btnHapusklmpok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapusklmpok.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnHapusklmpokMouseDragged(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(25, 16, 9));
        jLabel33.setText("Hapus");

        javax.swing.GroupLayout btnHapusklmpokLayout = new javax.swing.GroupLayout(btnHapusklmpok);
        btnHapusklmpok.setLayout(btnHapusklmpokLayout);
        btnHapusklmpokLayout.setHorizontalGroup(
            btnHapusklmpokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHapusklmpokLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnHapusklmpokLayout.setVerticalGroup(
            btnHapusklmpokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        kelompokPanel.add(btnHapusklmpok, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 90, 30));

        lblNamagrup2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblNamagrup2.setForeground(new java.awt.Color(239, 162, 92));
        lblNamagrup2.setText("Nama Kelompok");
        kelompokPanel.add(lblNamagrup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        txtNameKelompok.setBackground(new java.awt.Color(239, 162, 92));
        txtNameKelompok.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtNameKelompok.setForeground(new java.awt.Color(25, 16, 9));
        txtNameKelompok.setBorder(null);
        kelompokPanel.add(txtNameKelompok, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 130, 20));

        lblNamagrup3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblNamagrup3.setForeground(new java.awt.Color(239, 162, 92));
        lblNamagrup3.setText("ID Kelompok");
        kelompokPanel.add(lblNamagrup3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        mainPanel.add(kelompokPanel, "card3");

        settingPanel.setBackground(new java.awt.Color(25, 16, 9));
        settingPanel.setPreferredSize(new java.awt.Dimension(767, 468));

        lblEmail.setBackground(new java.awt.Color(239, 162, 92));
        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(239, 162, 92));
        lblEmail.setText("EMAIL :");

        txtEmail.setBackground(new java.awt.Color(133, 136, 107));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(25, 16, 9));
        txtEmail.setBorder(null);

        lblUsername.setBackground(new java.awt.Color(239, 162, 92));
        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(239, 162, 92));
        lblUsername.setText("USERNAME :");

        txtUsernameSetting.setBackground(new java.awt.Color(133, 136, 107));
        txtUsernameSetting.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtUsernameSetting.setForeground(new java.awt.Color(25, 16, 9));
        txtUsernameSetting.setBorder(null);

        lblPasswordSetting.setBackground(new java.awt.Color(239, 162, 92));
        lblPasswordSetting.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblPasswordSetting.setForeground(new java.awt.Color(239, 162, 92));
        lblPasswordSetting.setText("PASSWORD :");

        txtPasswordMenuFrame.setBackground(new java.awt.Color(133, 136, 107));
        txtPasswordMenuFrame.setForeground(new java.awt.Color(25, 16, 9));
        txtPasswordMenuFrame.setBorder(null);

        labelSetting.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        labelSetting.setForeground(new java.awt.Color(239, 162, 92));
        labelSetting.setText("Setting");

        btnUbahSetting.setBackground(new java.awt.Color(239, 162, 92));
        btnUbahSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(25, 16, 9));
        jLabel34.setText("Ubah");

        javax.swing.GroupLayout btnUbahSettingLayout = new javax.swing.GroupLayout(btnUbahSetting);
        btnUbahSetting.setLayout(btnUbahSettingLayout);
        btnUbahSettingLayout.setHorizontalGroup(
            btnUbahSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUbahSettingLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        btnUbahSettingLayout.setVerticalGroup(
            btnUbahSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        btnResetSetting.setBackground(new java.awt.Color(236, 245, 192));
        btnResetSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(25, 16, 9));
        jLabel35.setText("Reset");

        javax.swing.GroupLayout btnResetSettingLayout = new javax.swing.GroupLayout(btnResetSetting);
        btnResetSetting.setLayout(btnResetSettingLayout);
        btnResetSettingLayout.setHorizontalGroup(
            btnResetSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnResetSettingLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        btnResetSettingLayout.setVerticalGroup(
            btnResetSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        btnHapusSetting.setBackground(new java.awt.Color(239, 162, 92));
        btnHapusSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(25, 16, 9));
        jLabel36.setText("Hapus");

        javax.swing.GroupLayout btnHapusSettingLayout = new javax.swing.GroupLayout(btnHapusSetting);
        btnHapusSetting.setLayout(btnHapusSettingLayout);
        btnHapusSettingLayout.setHorizontalGroup(
            btnHapusSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHapusSettingLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        btnHapusSettingLayout.setVerticalGroup(
            btnHapusSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        btnCloseSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/CLOSE.png"))); // NOI18N
        btnCloseSet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseSet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseSetMouseClicked(evt);
            }
        });

        btnMiniizeSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/MINIMIZE.png"))); // NOI18N
        btnMiniizeSet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMiniizeSet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMiniizeSetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingPanelLayout.createSequentialGroup()
                        .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPasswordSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(settingPanelLayout.createSequentialGroup()
                                    .addComponent(btnUbahSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnHapusSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnResetSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtUsernameSetting, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelSetting, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPasswordMenuFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingPanelLayout.createSequentialGroup()
                        .addComponent(btnMiniizeSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCloseSet)
                        .addContainerGap())))
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCloseSet)
                    .addComponent(btnMiniizeSet))
                .addGap(33, 33, 33)
                .addComponent(labelSetting)
                .addGap(30, 30, 30)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsernameSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblPasswordSetting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPasswordMenuFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUbahSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        mainPanel.add(settingPanel, "card4");

        aboutPanelFix.setBackground(new java.awt.Color(25, 16, 9));
        aboutPanelFix.setPreferredSize(new java.awt.Dimension(767, 468));

        lblMinimizeAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/MINIMIZE.png"))); // NOI18N
        lblMinimizeAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizeAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeAboutMouseClicked(evt);
            }
        });

        lblCloseAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/CLOSE.png"))); // NOI18N
        lblCloseAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCloseAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseAboutMouseClicked(evt);
            }
        });

        lblLogoAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/logo.png"))); // NOI18N

        lblAboutNama.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblAboutNama.setForeground(new java.awt.Color(239, 162, 92));
        lblAboutNama.setText("Aplikasi Kocok Arisan");

        lblAboutVersi.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblAboutVersi.setForeground(new java.awt.Color(239, 162, 92));
        lblAboutVersi.setText("version 3.3.0");

        lblAboutDeveloped.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblAboutDeveloped.setForeground(new java.awt.Color(239, 162, 92));
        lblAboutDeveloped.setText("develoved By : Kelompok 1");

        javax.swing.GroupLayout aboutPanelFixLayout = new javax.swing.GroupLayout(aboutPanelFix);
        aboutPanelFix.setLayout(aboutPanelFixLayout);
        aboutPanelFixLayout.setHorizontalGroup(
            aboutPanelFixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelFixLayout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addGroup(aboutPanelFixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelFixLayout.createSequentialGroup()
                        .addComponent(lblMinimizeAbout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCloseAbout)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelFixLayout.createSequentialGroup()
                        .addGroup(aboutPanelFixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aboutPanelFixLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblLogoAbout)
                                .addGap(163, 163, 163))
                            .addComponent(lblAboutNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelFixLayout.createSequentialGroup()
                                .addComponent(lblAboutVersi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelFixLayout.createSequentialGroup()
                                .addComponent(lblAboutDeveloped, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)))
                        .addGap(152, 152, 152))))
        );
        aboutPanelFixLayout.setVerticalGroup(
            aboutPanelFixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelFixLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutPanelFixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMinimizeAbout)
                    .addComponent(lblCloseAbout))
                .addGap(120, 120, 120)
                .addComponent(lblLogoAbout)
                .addGap(18, 18, 18)
                .addComponent(lblAboutNama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAboutVersi, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAboutDeveloped)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        mainPanel.add(aboutPanelFix, "card5");

        tambahAnggotaPanel1.setBackground(new java.awt.Color(25, 16, 9));
        tambahAnggotaPanel1.setPreferredSize(new java.awt.Dimension(767, 468));

        labelSetting10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        labelSetting10.setForeground(new java.awt.Color(239, 162, 92));
        labelSetting10.setText("Anggota");

        btnUbahAnggota.setBackground(new java.awt.Color(239, 162, 92));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(25, 16, 9));
        jLabel47.setText("Ubah");

        javax.swing.GroupLayout btnUbahAnggotaLayout = new javax.swing.GroupLayout(btnUbahAnggota);
        btnUbahAnggota.setLayout(btnUbahAnggotaLayout);
        btnUbahAnggotaLayout.setHorizontalGroup(
            btnUbahAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUbahAnggotaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel47)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        btnUbahAnggotaLayout.setVerticalGroup(
            btnUbahAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        btnResetTambahAnngota.setBackground(new java.awt.Color(236, 245, 192));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(25, 16, 9));
        jLabel48.setText("Reset");

        javax.swing.GroupLayout btnResetTambahAnngotaLayout = new javax.swing.GroupLayout(btnResetTambahAnngota);
        btnResetTambahAnngota.setLayout(btnResetTambahAnngotaLayout);
        btnResetTambahAnngotaLayout.setHorizontalGroup(
            btnResetTambahAnngotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnResetTambahAnngotaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel48)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        btnResetTambahAnngotaLayout.setVerticalGroup(
            btnResetTambahAnngotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        btnHapusAnggota.setBackground(new java.awt.Color(239, 162, 92));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(25, 16, 9));
        jLabel50.setText("Hapus");

        javax.swing.GroupLayout btnHapusAnggotaLayout = new javax.swing.GroupLayout(btnHapusAnggota);
        btnHapusAnggota.setLayout(btnHapusAnggotaLayout);
        btnHapusAnggotaLayout.setHorizontalGroup(
            btnHapusAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHapusAnggotaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel50)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        btnHapusAnggotaLayout.setVerticalGroup(
            btnHapusAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        lblMinimaselogoTabbahAnngota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/MINIMIZE.png"))); // NOI18N
        lblMinimaselogoTabbahAnngota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimaselogoTabbahAnngota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimaselogoTabbahAnngotaMouseClicked(evt);
            }
        });

        lblExitTambbahAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/CLOSE.png"))); // NOI18N
        lblExitTambbahAnggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExitTambbahAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitTambbahAnggotaMouseClicked(evt);
            }
        });

        lblIdanggotaTabahAnggota.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblIdanggotaTabahAnggota.setForeground(new java.awt.Color(239, 162, 92));
        lblIdanggotaTabahAnggota.setText("ID Anggota           :");

        lblNamaanggotaUbah.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNamaanggotaUbah.setForeground(new java.awt.Color(239, 162, 92));
        lblNamaanggotaUbah.setText("Nama Anggota     :");

        lblAlamatTambahAnggota.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblAlamatTambahAnggota.setForeground(new java.awt.Color(239, 162, 92));
        lblAlamatTambahAnggota.setText("Alamat           :");

        lblIkutarisanTambahAnggota.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblIkutarisanTambahAnggota.setForeground(new java.awt.Color(239, 162, 92));
        lblIkutarisanTambahAnggota.setText("Ikut Arisan       :");

        txtIdanggota.setBackground(new java.awt.Color(239, 162, 92));
        txtIdanggota.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtIdanggota.setForeground(new java.awt.Color(25, 16, 9));
        txtIdanggota.setText("10116487");
        txtIdanggota.setBorder(null);

        txtNamaanggota.setBackground(new java.awt.Color(239, 162, 92));
        txtNamaanggota.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNamaanggota.setForeground(new java.awt.Color(25, 16, 9));
        txtNamaanggota.setText("Huldan ganteng");
        txtNamaanggota.setBorder(null);

        txtAlamatTambahAnggota.setBackground(new java.awt.Color(239, 162, 92));
        txtAlamatTambahAnggota.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtAlamatTambahAnggota.setForeground(new java.awt.Color(25, 16, 9));
        txtAlamatTambahAnggota.setText("Jl. Kebon Kawung Pasir Kaliki");
        txtAlamatTambahAnggota.setBorder(null);

        listIkutarisanTambahAnggota.setBackground(new java.awt.Color(239, 162, 92));
        listIkutarisanTambahAnggota.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        listIkutarisanTambahAnggota.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listIkutarisanTambahAnggota);

        tblTambahanggotaTambbahAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblTambahanggotaTambbahAnggota);

        lblMulaiTambahAnggita.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblMulaiTambahAnggita.setForeground(new java.awt.Color(236, 245, 192));
        lblMulaiTambahAnggita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/MULAI.png"))); // NOI18N
        lblMulaiTambahAnggita.setText("MULAI");
        lblMulaiTambahAnggita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMulaiTambahAnggitaMouseClicked(evt);
            }
        });

        btnTambahAnggota.setBackground(new java.awt.Color(239, 162, 92));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(25, 16, 9));
        jLabel49.setText("Tambah");

        javax.swing.GroupLayout btnTambahAnggotaLayout = new javax.swing.GroupLayout(btnTambahAnggota);
        btnTambahAnggota.setLayout(btnTambahAnggotaLayout);
        btnTambahAnggotaLayout.setHorizontalGroup(
            btnTambahAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTambahAnggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnTambahAnggotaLayout.setVerticalGroup(
            btnTambahAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tambahAnggotaPanel1Layout = new javax.swing.GroupLayout(tambahAnggotaPanel1);
        tambahAnggotaPanel1.setLayout(tambahAnggotaPanel1Layout);
        tambahAnggotaPanel1Layout.setHorizontalGroup(
            tambahAnggotaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahAnggotaPanel1Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(tambahAnggotaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahAnggotaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tambahAnggotaPanel1Layout.createSequentialGroup()
                            .addComponent(labelSetting10, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(381, 381, 381))
                        .addGroup(tambahAnggotaPanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(tambahAnggotaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(tambahAnggotaPanel1Layout.createSequentialGroup()
                                    .addGroup(tambahAnggotaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNamaanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(tambahAnggotaPanel1Layout.createSequentialGroup()
                                            .addGroup(tambahAnggotaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblNamaanggotaUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblIdanggotaTabahAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(12, 12, 12)
                                            .addComponent(txtIdanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(27, 27, 27)
                                    .addGroup(tambahAnggotaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(tambahAnggotaPanel1Layout.createSequentialGroup()
                                            .addComponent(lblAlamatTambahAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtAlamatTambahAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(tambahAnggotaPanel1Layout.createSequentialGroup()
                                            .addComponent(lblIkutarisanTambahAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(43, 43, 43)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahAnggotaPanel1Layout.createSequentialGroup()
                                    .addComponent(btnTambahAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(btnUbahAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(btnHapusAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(btnResetTambahAnngota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahAnggotaPanel1Layout.createSequentialGroup()
                        .addComponent(lblMulaiTambahAnggita, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahAnggotaPanel1Layout.createSequentialGroup()
                        .addComponent(lblMinimaselogoTabbahAnngota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblExitTambbahAnggota)
                        .addContainerGap())))
        );
        tambahAnggotaPanel1Layout.setVerticalGroup(
            tambahAnggotaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahAnggotaPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahAnggotaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMinimaselogoTabbahAnngota)
                    .addComponent(lblExitTambbahAnggota))
                .addGap(33, 33, 33)
                .addComponent(labelSetting10)
                .addGap(39, 39, 39)
                .addGroup(tambahAnggotaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdanggotaTabahAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlamatTambahAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlamatTambahAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(tambahAnggotaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaanggotaUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIkutarisanTambahAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(tambahAnggotaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnResetTambahAnngota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapusAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbahAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambahAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(lblMulaiTambahAnggita, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        mainPanel.add(tambahAnggotaPanel1, "card6");

        tampilPanel.setBackground(new java.awt.Color(25, 16, 9));
        tampilPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));

        btnTampilPanel.setBackground(new java.awt.Color(236, 245, 192));
        btnTampilPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTampilPanel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnTampilPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTampilPanelMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(25, 16, 9));
        jLabel11.setText("CETAK");

        javax.swing.GroupLayout btnTampilPanelLayout = new javax.swing.GroupLayout(btnTampilPanel);
        btnTampilPanel.setLayout(btnTampilPanelLayout);
        btnTampilPanelLayout.setHorizontalGroup(
            btnTampilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTampilPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        btnTampilPanelLayout.setVerticalGroup(
            btnTampilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        btnKembali.setBackground(new java.awt.Color(239, 162, 92));
        btnKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(239, 162, 92));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(25, 16, 9));
        jLabel19.setText("KEMBALI");

        javax.swing.GroupLayout btnKembaliLayout = new javax.swing.GroupLayout(btnKembali);
        btnKembali.setLayout(btnKembaliLayout);
        btnKembaliLayout.setHorizontalGroup(
            btnKembaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnKembaliLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnKembaliLayout.setVerticalGroup(
            btnKembaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        tabelTampil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel1.setViewportView(tabelTampil);

        lblMinimalieTmpilKelompok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/MINIMIZE.png"))); // NOI18N
        lblMinimalieTmpilKelompok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimalieTmpilKelompok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimalieTmpilKelompokMouseClicked(evt);
            }
        });

        lblExitTampilK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/CLOSE.png"))); // NOI18N
        lblExitTampilK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExitTampilK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitTampilKMouseClicked(evt);
            }
        });

        lblNamagrup4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNamagrup4.setForeground(new java.awt.Color(239, 162, 92));
        lblNamagrup4.setText("Tampil Kelompok");

        javax.swing.GroupLayout tampilPanelLayout = new javax.swing.GroupLayout(tampilPanel);
        tampilPanel.setLayout(tampilPanelLayout);
        tampilPanelLayout.setHorizontalGroup(
            tampilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilPanelLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(tampilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilPanelLayout.createSequentialGroup()
                        .addGroup(tampilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamagrup4)
                            .addGroup(tampilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(tampilPanelLayout.createSequentialGroup()
                                    .addComponent(btnTampilPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilPanelLayout.createSequentialGroup()
                        .addComponent(lblMinimalieTmpilKelompok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblExitTampilK)
                        .addContainerGap())))
        );
        tampilPanelLayout.setVerticalGroup(
            tampilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tampilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMinimalieTmpilKelompok)
                    .addComponent(lblExitTampilK))
                .addGap(37, 37, 37)
                .addComponent(lblNamagrup4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(tabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(tampilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTampilPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        mainPanel.add(tampilPanel, "card7");

        panelMain.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 0, 710, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKelompokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonKelompokMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonKelompokMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        // TODO add your handling code here:
        
        PanelKeKiri();
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(panelUtama);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingMouseClicked
        // TODO add your handling code here:
        PanelKeKiri();
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(settingPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_lblSettingMouseClicked

    private void lblAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseClicked
        // TODO add your handling code here:
        PanelKeKiri();
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(aboutPanelFix);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_lblAboutMouseClicked

    private void lblKelompokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKelompokMouseClicked
        // TODO add your handling code here:
        PanelKeKiri();
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(kelompokPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_lblKelompokMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        // TODO add your handling code here:
      //  popUpFrameTambah n  = new popUpFrameTambah();
      //  n.setVisible(true);
        
       
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnResetKelompokMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetKelompokMouseDragged
        // TODO add your handling code here:
      //  popUpFrameUbah n  = new popUpFrameUbah();
       // n.setVisible(true);

    }//GEN-LAST:event_btnResetKelompokMouseDragged

    private void menuPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanelMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuPanelMouseExited

    private void mainPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseEntered
        // TODO add your handling code here:
        PanelKeKiri();
    }//GEN-LAST:event_mainPanelMouseEntered

    private void buttonLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLogOutMouseClicked
        // TODO add your handling code here:
        logouFrame n = new logouFrame();
        n.setVisible(true);
        
    }//GEN-LAST:event_buttonLogOutMouseClicked

    private void labelCloseUtamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCloseUtamaMouseClicked
        // TODO add your handling code here:
        dialogFrame n  = new dialogFrame();
        n.setVisible(true);
    }//GEN-LAST:event_labelCloseUtamaMouseClicked

    private void closeKelompokPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeKelompokPanelMouseClicked
        // TODO add your handling code here:
        dialogFrame n  = new dialogFrame();
        n.setVisible(true);
    }//GEN-LAST:event_closeKelompokPanelMouseClicked

    private void btnCloseSetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseSetMouseClicked
        // TODO add your handling code here:
        dialogFrame n  = new dialogFrame();
        n.setVisible(true);
    }//GEN-LAST:event_btnCloseSetMouseClicked

    private void lblCloseAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseAboutMouseClicked
        // TODO add your handling code here:
        dialogFrame n  = new dialogFrame();
        n.setVisible(true);
    }//GEN-LAST:event_lblCloseAboutMouseClicked

    private void labelMinimizeUtamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeUtamaMouseClicked
        // TODO add your handling code here:
        this.setState(menuFrame.ICONIFIED);
    }//GEN-LAST:event_labelMinimizeUtamaMouseClicked

    private void minimizeKelompokPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeKelompokPanelMouseClicked
        // TODO add your handling code here:
        this.setState(menuFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeKelompokPanelMouseClicked

    private void btnMiniizeSetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniizeSetMouseClicked
        // TODO add your handling code here:
        this.setState(menuFrame.ICONIFIED);
    }//GEN-LAST:event_btnMiniizeSetMouseClicked

    private void lblMinimizeAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeAboutMouseClicked
        // TODO add your handling code here:
        this.setState(menuFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeAboutMouseClicked

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        // TODO add your handling code here:
        PanelKeKanan();
        PanelKeKiri();
    }//GEN-LAST:event_btnMenuMouseClicked

    private void lblMinimaselogoTabbahAnngotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimaselogoTabbahAnngotaMouseClicked
        // TODO add your handling code here:
        this.setState(menuFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimaselogoTabbahAnngotaMouseClicked

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        // TODO add your handling code here:
        PanelKeKiri();
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(kelompokPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_btnKembaliMouseClicked

    private void btnTampilPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTampilPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTampilPanelMouseClicked

    private void lblMulaiTambahAnggitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMulaiTambahAnggitaMouseClicked
        // TODO add your handling code here:
        PanelKeKiri();
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tampilPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_lblMulaiTambahAnggitaMouseClicked

    private void txtJumlahAnggotaklmpokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahAnggotaklmpokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahAnggotaklmpokActionPerformed

    private void btnUbahklmpokMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahklmpokMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahklmpokMouseDragged

    private void btnHapusklmpokMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusklmpokMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusklmpokMouseDragged

    private void btnTampilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTampilMouseClicked
        // TODO add your handling code here:
         mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tambahAnggotaPanel1);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_btnTampilMouseClicked

    private void lblExitTambbahAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitTambbahAnggotaMouseClicked
        // TODO add your handling code here:
        dialogFrame n  = new dialogFrame();
        n.setVisible(true);
    }//GEN-LAST:event_lblExitTambbahAnggotaMouseClicked

    private void lblMinimaselogoTabbahAnngota1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimaselogoTabbahAnngota1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMinimaselogoTabbahAnngota1MouseClicked

    private void lblExitTambbahAnggota1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitTambbahAnggota1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblExitTambbahAnggota1MouseClicked

    private void lblMinimalieTmpilKelompokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimalieTmpilKelompokMouseClicked
        // TODO add your handling code here:
        this.setState(menuFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimalieTmpilKelompokMouseClicked

    private void lblExitTampilKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitTampilKMouseClicked
        // TODO add your handling code here:
        dialogFrame n  = new dialogFrame();
        n.setVisible(true);
    }//GEN-LAST:event_lblExitTampilKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanelFix;
    private javax.swing.JLabel btnCloseSet;
    private javax.swing.JPanel btnHapusAnggota;
    private javax.swing.JPanel btnHapusSetting;
    private javax.swing.JPanel btnHapusklmpok;
    private javax.swing.JPanel btnKembali;
    private javax.swing.JLabel btnMenu;
    private javax.swing.JLabel btnMiniizeSet;
    private javax.swing.JPanel btnResetKelompok;
    private javax.swing.JPanel btnResetSetting;
    private javax.swing.JPanel btnResetTambahAnngota;
    private javax.swing.JPanel btnTambah;
    private javax.swing.JPanel btnTambahAnggota;
    private javax.swing.JPanel btnTampil;
    private javax.swing.JPanel btnTampilPanel;
    private javax.swing.JPanel btnUbahAnggota;
    private javax.swing.JPanel btnUbahSetting;
    private javax.swing.JPanel btnUbahklmpok;
    private javax.swing.JLabel buttonAbout;
    private javax.swing.JLabel buttonHome1;
    private javax.swing.JLabel buttonKelompok;
    private javax.swing.JLabel buttonLogOut;
    private javax.swing.JLabel buttonSetting;
    private javax.swing.JLabel closeKelompokPanel;
    private javax.swing.JComboBox<String> combo3;
    private javax.swing.JComboBox<String> combo4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel kelompokPanel;
    private javax.swing.JLabel labelAdmin;
    private javax.swing.JLabel labelAngka;
    private javax.swing.JLabel labelCloseUtama;
    private javax.swing.JLabel labelMinimizeUtama;
    private javax.swing.JLabel labelSetting;
    private javax.swing.JLabel labelSetting10;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblAboutDeveloped;
    private javax.swing.JLabel lblAboutNama;
    private javax.swing.JLabel lblAboutText;
    private javax.swing.JLabel lblAboutVersi;
    private javax.swing.JLabel lblAlamatTambahAnggota;
    private javax.swing.JLabel lblAnggota1;
    private javax.swing.JLabel lblCloseAbout;
    private javax.swing.JLabel lblDuaHome;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblExitTambbahAnggota;
    private javax.swing.JLabel lblExitTambbahAnggota1;
    private javax.swing.JLabel lblExitTampilK;
    private javax.swing.JLabel lblHalloText;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblHomeKelompok;
    private javax.swing.JLabel lblHomeText;
    private javax.swing.JLabel lblIdanggotaTabahAnggota;
    private javax.swing.JLabel lblIkutarisanTambahAnggota;
    private javax.swing.JLabel lblJadwal1;
    private javax.swing.JLabel lblJumlah1;
    private javax.swing.JLabel lblKelompok;
    private javax.swing.JLabel lblKelompokText;
    private javax.swing.JLabel lblLogoAbout;
    private javax.swing.JLabel lblLogoAdmin;
    private javax.swing.JLabel lblMinimalieTmpilKelompok;
    private javax.swing.JLabel lblMinimaselogoTabbahAnngota;
    private javax.swing.JLabel lblMinimaselogoTabbahAnngota1;
    private javax.swing.JLabel lblMinimizeAbout;
    private javax.swing.JLabel lblMulaiTambahAnggita;
    private javax.swing.JLabel lblNamaanggotaUbah;
    private javax.swing.JLabel lblNamagrup1;
    private javax.swing.JLabel lblNamagrup2;
    private javax.swing.JLabel lblNamagrup3;
    private javax.swing.JLabel lblNamagrup4;
    private javax.swing.JLabel lblPasswordSetting;
    private javax.swing.JLabel lblSetting;
    private javax.swing.JLabel lblSettingtext;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JList<String> listIkutarisanTambahAnggota;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel minimizeKelompokPanel;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JSeparator separatorHome;
    private javax.swing.JSeparator separatorKelompok;
    private javax.swing.JSeparator separatorPanelUtama;
    private javax.swing.JSeparator separatorSetting;
    private javax.swing.JSeparator seperatorAbout;
    private javax.swing.JPanel settingPanel;
    private javax.swing.JScrollPane tabel;
    private javax.swing.JScrollPane tabel1;
    private javax.swing.JTable tabelTampil;
    private javax.swing.JPanel tambahAnggotaPanel1;
    private javax.swing.JPanel tampilPanel;
    private javax.swing.JTable tblTambahanggotaTambbahAnggota;
    private javax.swing.JTextField txtAlamatTambahAnggota;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdKelompok;
    private javax.swing.JTextField txtIdanggota;
    private javax.swing.JTextField txtJumlahAnggotaklmpok;
    private javax.swing.JFormattedTextField txtJumlahSetoranklmpk;
    private javax.swing.JTextField txtNamaanggota;
    private javax.swing.JTextField txtNameKelompok;
    private javax.swing.JPasswordField txtPasswordMenuFrame;
    private javax.swing.JTextField txtUsernameSetting;
    // End of variables declaration//GEN-END:variables
}