/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.kelompok1.kocokarisan.view;

/**
 *
 * @author HLDN
 */
public class popUpFrameTambah extends javax.swing.JFrame {

    /**
     * Creates new form popUpFrame
     */
    public popUpFrameTambah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupPanelutamaTambah = new javax.swing.JPanel();
        popupPanelTambah = new javax.swing.JPanel();
        lblJumlah = new javax.swing.JLabel();
        lblJadwal = new javax.swing.JLabel();
        lblAnggota = new javax.swing.JLabel();
        lblNamagrup = new javax.swing.JLabel();
        txtNameGrup = new javax.swing.JTextField();
        txtJumlahAnggota = new javax.swing.JTextField();
        txtJumlahSetoran = new javax.swing.JFormattedTextField();
        combo1 = new javax.swing.JComboBox<>();
        combo2 = new javax.swing.JComboBox<>();
        btnBatalFrametmbh = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnTambahFrametmbh = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnResetFrametmbh = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        popupPanelutamaTambah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        popupPanelTambah.setBackground(new java.awt.Color(25, 16, 9));
        popupPanelTambah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));

        lblJumlah.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblJumlah.setForeground(new java.awt.Color(239, 162, 92));
        lblJumlah.setText("Jumlah Setoran");

        lblJadwal.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblJadwal.setForeground(new java.awt.Color(239, 162, 92));
        lblJadwal.setText("Jadwal");

        lblAnggota.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblAnggota.setForeground(new java.awt.Color(239, 162, 92));
        lblAnggota.setText("Jumlah Anggota");

        lblNamagrup.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblNamagrup.setForeground(new java.awt.Color(239, 162, 92));
        lblNamagrup.setText("Nama Grup");

        txtNameGrup.setBackground(new java.awt.Color(239, 162, 92));
        txtNameGrup.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtNameGrup.setForeground(new java.awt.Color(25, 16, 9));
        txtNameGrup.setBorder(null);

        txtJumlahAnggota.setBackground(new java.awt.Color(239, 162, 92));
        txtJumlahAnggota.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtJumlahAnggota.setForeground(new java.awt.Color(25, 16, 9));
        txtJumlahAnggota.setBorder(null);

        txtJumlahSetoran.setBackground(new java.awt.Color(239, 162, 92));
        txtJumlahSetoran.setBorder(null);
        txtJumlahSetoran.setForeground(new java.awt.Color(25, 16, 9));
        try {
            txtJumlahSetoran.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("Rp. ###,###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        combo1.setBackground(new java.awt.Color(239, 162, 92));
        combo1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combo2.setBackground(new java.awt.Color(239, 162, 92));
        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBatalFrametmbh.setBackground(new java.awt.Color(236, 245, 192));
        btnBatalFrametmbh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatalFrametmbh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalFrametmbhMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(25, 16, 9));
        jLabel10.setText("BATAL");

        javax.swing.GroupLayout btnBatalFrametmbhLayout = new javax.swing.GroupLayout(btnBatalFrametmbh);
        btnBatalFrametmbh.setLayout(btnBatalFrametmbhLayout);
        btnBatalFrametmbhLayout.setHorizontalGroup(
            btnBatalFrametmbhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBatalFrametmbhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnBatalFrametmbhLayout.setVerticalGroup(
            btnBatalFrametmbhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        btnTambahFrametmbh.setBackground(new java.awt.Color(236, 245, 192));
        btnTambahFrametmbh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahFrametmbh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahFrametmbhMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(25, 16, 9));
        jLabel16.setText("TAMBAH");

        javax.swing.GroupLayout btnTambahFrametmbhLayout = new javax.swing.GroupLayout(btnTambahFrametmbh);
        btnTambahFrametmbh.setLayout(btnTambahFrametmbhLayout);
        btnTambahFrametmbhLayout.setHorizontalGroup(
            btnTambahFrametmbhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTambahFrametmbhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnTambahFrametmbhLayout.setVerticalGroup(
            btnTambahFrametmbhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        btnResetFrametmbh.setBackground(new java.awt.Color(239, 162, 92));
        btnResetFrametmbh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel17.setBackground(new java.awt.Color(239, 162, 92));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(25, 16, 9));
        jLabel17.setText("RESET");

        javax.swing.GroupLayout btnResetFrametmbhLayout = new javax.swing.GroupLayout(btnResetFrametmbh);
        btnResetFrametmbh.setLayout(btnResetFrametmbhLayout);
        btnResetFrametmbhLayout.setHorizontalGroup(
            btnResetFrametmbhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnResetFrametmbhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnResetFrametmbhLayout.setVerticalGroup(
            btnResetFrametmbhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout popupPanelTambahLayout = new javax.swing.GroupLayout(popupPanelTambah);
        popupPanelTambah.setLayout(popupPanelTambahLayout);
        popupPanelTambahLayout.setHorizontalGroup(
            popupPanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupPanelTambahLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(popupPanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamagrup)
                    .addComponent(lblJadwal)
                    .addComponent(lblJumlah)
                    .addComponent(lblAnggota))
                .addGap(63, 63, 63)
                .addGroup(popupPanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtJumlahAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(popupPanelTambahLayout.createSequentialGroup()
                        .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(combo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtNameGrup, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(txtJumlahSetoran))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupPanelTambahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTambahFrametmbh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBatalFrametmbh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResetFrametmbh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        popupPanelTambahLayout.setVerticalGroup(
            popupPanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupPanelTambahLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(popupPanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamagrup)
                    .addGroup(popupPanelTambahLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtNameGrup, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(popupPanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnggota)
                    .addGroup(popupPanelTambahLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtJumlahAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(popupPanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(popupPanelTambahLayout.createSequentialGroup()
                        .addComponent(lblJumlah)
                        .addGap(18, 18, 18))
                    .addGroup(popupPanelTambahLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtJumlahSetoran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(popupPanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(popupPanelTambahLayout.createSequentialGroup()
                        .addGroup(popupPanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJadwal)
                            .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambahFrametmbh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupPanelTambahLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(popupPanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBatalFrametmbh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResetFrametmbh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );

        popupPanelutamaTambah.add(popupPanelTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(popupPanelutamaTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(popupPanelutamaTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalFrametmbhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalFrametmbhMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBatalFrametmbhMouseClicked

    private void btnTambahFrametmbhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahFrametmbhMouseClicked
        // TODO add your handling code here:
        tambahFrame n = new tambahFrame();
                n.setVisible(true);
    }//GEN-LAST:event_btnTambahFrametmbhMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popUpFrameTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popUpFrameTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popUpFrameTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popUpFrameTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popUpFrameTambah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBatalFrametmbh;
    private javax.swing.JPanel btnResetFrametmbh;
    private javax.swing.JPanel btnTambahFrametmbh;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel lblAnggota;
    private javax.swing.JLabel lblJadwal;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblNamagrup;
    private javax.swing.JPanel popupPanelTambah;
    private javax.swing.JPanel popupPanelutamaTambah;
    private javax.swing.JTextField txtJumlahAnggota;
    private javax.swing.JFormattedTextField txtJumlahSetoran;
    private javax.swing.JTextField txtNameGrup;
    // End of variables declaration//GEN-END:variables
}
