/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.kelompok1.kocokarisan.view;

import edu.kelompok1.kocokarisan.controller.AdminController;
import edu.kelompok1.kocokarisan.database.ArisanYukDatabase;
import edu.kelompok1.kocokarisan.entity.Admin;
import edu.kelompok1.kocokarisan.event.AdminListener;
import edu.kelompok1.kocokarisan.model.AdminModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author HLDN
 */
public class registerFrame extends javax.swing.JFrame implements AdminListener{
public final String url = "jdbc:mysql://localhost:3306/arisanyuk";
    public final String user = "root";
    public final String pass = "";

    Connection con;
    Statement stmt;
    ResultSet rs;
    String sql;
    
    private AdminModel model;
    private AdminController controller;
    
    public registerFrame() {
        initComponents();
        ArisanYukDatabase DB = new ArisanYukDatabase();
        DB.config();
        con = DB.con;
        stmt = DB.stmt;
        
        model =  new AdminModel();
        model.setListener(this);
        
        controller = new AdminController();
        controller.setModel(model);
    }

    public JPasswordField getTxtPassword() {
        return txtPasswordRegisterF;
    }

    public void setTxtPassword(JPasswordField txtPassword) {
        this.txtPasswordRegisterF = txtPassword;
    }

    public JPasswordField getTxtPasswordRegister() {
        return txtPasswordmendaftarRegisterF;
    }

    public void setTxtPasswordRegister(JPasswordField txtPasswordRegister) {
        this.txtPasswordmendaftarRegisterF = txtPasswordRegister;
    }

    public JTextField getTxtUsername() {
        return txtUsernameRegisterF;
    }

    public void setTxtUsername(JTextField txtUsername) {
        this.txtUsernameRegisterF = txtUsername;
    }

    public JTextField getTxtUsernameRegister() {
        return txtUsernamemendaftarRegisterF;
    }

    public void setTxtUsernameRegister(JTextField txtUsernameRegister) {
        this.txtUsernamemendaftarRegisterF = txtUsernameRegister;
    }

    public JTextField getTxtEmailRegister() {
        return txtEmailendaftarRegisterF;
    }

    public void setTxtEmailRegister(JTextField txtEmailRegister) {
        this.txtEmailendaftarRegisterF = txtEmailRegister;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblUsernaeRegisterF = new javax.swing.JLabel();
        txtUsernameRegisterF = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblPasswodRegisterF = new javax.swing.JLabel();
        txtPasswordRegisterF = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        btnLoginRegisterF = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtUsernae = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtUsernamemendaftarRegisterF = new javax.swing.JTextField();
        lblEmailmendaftarRegisterF = new javax.swing.JLabel();
        lblUsernamemendaftarRegisterF = new javax.swing.JLabel();
        txtEmailendaftarRegisterF = new javax.swing.JTextField();
        lblPasswordmendaftarRegisterF = new javax.swing.JLabel();
        txtPasswordmendaftarRegisterF = new javax.swing.JPasswordField();
        checkSetujumendaftarRegisterF = new javax.swing.JCheckBox();
        btnRegister = new javax.swing.JLabel();
        lblExitmendaftarRegisterF = new javax.swing.JLabel();
        lblMinimendaftarRegisterF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerPanel.setBackground(new java.awt.Color(25, 16, 9));
        registerPanel.setPreferredSize(new java.awt.Dimension(767, 468));

        jPanel4.setBackground(new java.awt.Color(25, 16, 9));

        lblUsernaeRegisterF.setBackground(new java.awt.Color(239, 162, 92));
        lblUsernaeRegisterF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsernaeRegisterF.setForeground(new java.awt.Color(239, 162, 92));
        lblUsernaeRegisterF.setText("USERNAME");

        txtUsernameRegisterF.setBackground(new java.awt.Color(25, 16, 9));
        txtUsernameRegisterF.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtUsernameRegisterF.setForeground(new java.awt.Color(133, 136, 107));
        txtUsernameRegisterF.setText("HULDAN");
        txtUsernameRegisterF.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(133, 136, 107));
        jSeparator2.setForeground(new java.awt.Color(133, 136, 107));

        lblPasswodRegisterF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPasswodRegisterF.setForeground(new java.awt.Color(239, 162, 92));
        lblPasswodRegisterF.setText("PASSWORD");

        txtPasswordRegisterF.setBackground(new java.awt.Color(25, 16, 9));
        txtPasswordRegisterF.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtPasswordRegisterF.setForeground(new java.awt.Color(133, 136, 107));
        txtPasswordRegisterF.setText("jPasswordField1");
        txtPasswordRegisterF.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(133, 136, 107));
        jSeparator4.setForeground(new java.awt.Color(133, 136, 107));

        btnLoginRegisterF.setBackground(new java.awt.Color(239, 162, 92));
        btnLoginRegisterF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoginRegisterF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginRegisterFMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(25, 16, 9));
        jLabel8.setText("LOGIN");

        javax.swing.GroupLayout btnLoginRegisterFLayout = new javax.swing.GroupLayout(btnLoginRegisterF);
        btnLoginRegisterF.setLayout(btnLoginRegisterFLayout);
        btnLoginRegisterFLayout.setHorizontalGroup(
            btnLoginRegisterFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLoginRegisterFLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        btnLoginRegisterFLayout.setVerticalGroup(
            btnLoginRegisterFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        txtUsernae.setText("jLabel21");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/PASSWORD.png"))); // NOI18N
        jLabel22.setText("jLabel21");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(lblUsernaeRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsernae, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(51, 51, 51)
                                    .addComponent(lblPasswodRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPasswordRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsernameRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(btnLoginRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(35, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(lblUsernaeRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsernae)
                .addGap(46, 46, 46)
                .addComponent(jLabel22)
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(182, 182, 182)
                    .addComponent(txtUsernameRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)
                    .addComponent(lblPasswodRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtPasswordRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnLoginRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(161, Short.MAX_VALUE)))
        );

        jPanel5.setBackground(new java.awt.Color(25, 16, 9));

        jSeparator5.setBackground(new java.awt.Color(133, 136, 107));
        jSeparator5.setForeground(new java.awt.Color(133, 136, 107));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel9.setBackground(new java.awt.Color(239, 162, 92));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(239, 162, 92));
        jLabel9.setText("MENDAFTAR");

        txtUsernamemendaftarRegisterF.setBackground(new java.awt.Color(133, 136, 107));
        txtUsernamemendaftarRegisterF.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtUsernamemendaftarRegisterF.setForeground(new java.awt.Color(25, 16, 9));
        txtUsernamemendaftarRegisterF.setBorder(null);

        lblEmailmendaftarRegisterF.setBackground(new java.awt.Color(239, 162, 92));
        lblEmailmendaftarRegisterF.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblEmailmendaftarRegisterF.setForeground(new java.awt.Color(239, 162, 92));
        lblEmailmendaftarRegisterF.setText("EMAIL :");

        lblUsernamemendaftarRegisterF.setBackground(new java.awt.Color(239, 162, 92));
        lblUsernamemendaftarRegisterF.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblUsernamemendaftarRegisterF.setForeground(new java.awt.Color(239, 162, 92));
        lblUsernamemendaftarRegisterF.setText("USERNAME :");

        txtEmailendaftarRegisterF.setBackground(new java.awt.Color(133, 136, 107));
        txtEmailendaftarRegisterF.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtEmailendaftarRegisterF.setForeground(new java.awt.Color(25, 16, 9));
        txtEmailendaftarRegisterF.setBorder(null);

        lblPasswordmendaftarRegisterF.setBackground(new java.awt.Color(239, 162, 92));
        lblPasswordmendaftarRegisterF.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblPasswordmendaftarRegisterF.setForeground(new java.awt.Color(239, 162, 92));
        lblPasswordmendaftarRegisterF.setText("PASSWORD :");

        txtPasswordmendaftarRegisterF.setBackground(new java.awt.Color(133, 136, 107));
        txtPasswordmendaftarRegisterF.setForeground(new java.awt.Color(25, 16, 9));
        txtPasswordmendaftarRegisterF.setBorder(null);

        checkSetujumendaftarRegisterF.setBackground(new java.awt.Color(25, 16, 9));
        checkSetujumendaftarRegisterF.setForeground(new java.awt.Color(133, 136, 107));
        checkSetujumendaftarRegisterF.setText("saya setuju dengan semua persyaratan");

        btnRegister.setBackground(new java.awt.Color(239, 162, 92));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(239, 162, 92));
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/NEXT.png"))); // NOI18N
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });

        lblExitmendaftarRegisterF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/CLOSE.png"))); // NOI18N
        lblExitmendaftarRegisterF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblMinimendaftarRegisterF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok1/kocokarisan/icon/MINIMIZE.png"))); // NOI18N
        lblMinimendaftarRegisterF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimendaftarRegisterF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimendaftarRegisterFMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(checkSetujumendaftarRegisterF, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addGap(177, 177, 177))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegister)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUsernamemendaftarRegisterF)
                                .addComponent(lblEmailmendaftarRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmailendaftarRegisterF)
                                .addComponent(lblUsernamemendaftarRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPasswordmendaftarRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPasswordmendaftarRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(99, 99, 99))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimendaftarRegisterF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblExitmendaftarRegisterF)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblExitmendaftarRegisterF)
                    .addComponent(lblMinimendaftarRegisterF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmailmendaftarRegisterF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailendaftarRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lblUsernamemendaftarRegisterF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsernamemendaftarRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblPasswordmendaftarRegisterF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPasswordmendaftarRegisterF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkSetujumendaftarRegisterF))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        // TODO add your handling code here:
        controller.insertAdmin(this);

        /*menuFrame n = new menuFrame();
        n.setVisible(true);
        dispose();*/


    }//GEN-LAST:event_btnRegisterMouseClicked

    private void btnLoginRegisterFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginRegisterFMouseClicked
        // TODO add your handling code here:
        Boolean cek = Boolean.FALSE;
        if (txtUsernameRegisterF.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Nama belum di isi");
        } else if (new String(txtPasswordRegisterF.getPassword()).trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Password belum di isi");
        } else {
            cek=Boolean.TRUE;
        }
        try {
            sql="SELECT * FROM ADMIN WHERE USERNAME='" +txtUsernameRegisterF.getText()+ "' AND PASSWORD='" + new String(txtPasswordRegisterF.getPassword()) + "'";
            rs = stmt.executeQuery(sql);
            if(cek) {
            if(rs.next()) {
                if(txtUsernameRegisterF.getText().equals(rs.getString("USERNAME")) && new String(txtPasswordRegisterF.getPassword()).equals(rs.getString("PASSWORD"))) {
                    menuFrame n  = new menuFrame();
                    n.setVisible(true);
        dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usename atau Password Salah");
            }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnLoginRegisterFMouseClicked

    private void lblMinimendaftarRegisterFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimendaftarRegisterFMouseClicked
        // TODO add your handling code here:
        this.setState(menuFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimendaftarRegisterFMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnLoginRegisterF;
    private javax.swing.JLabel btnRegister;
    private javax.swing.JCheckBox checkSetujumendaftarRegisterF;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblEmailmendaftarRegisterF;
    private javax.swing.JLabel lblExitmendaftarRegisterF;
    private javax.swing.JLabel lblMinimendaftarRegisterF;
    private javax.swing.JLabel lblPasswodRegisterF;
    private javax.swing.JLabel lblPasswordmendaftarRegisterF;
    private javax.swing.JLabel lblUsernaeRegisterF;
    private javax.swing.JLabel lblUsernamemendaftarRegisterF;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JTextField txtEmailendaftarRegisterF;
    private javax.swing.JPasswordField txtPasswordRegisterF;
    private javax.swing.JPasswordField txtPasswordmendaftarRegisterF;
    private javax.swing.JLabel txtUsernae;
    private javax.swing.JTextField txtUsernameRegisterF;
    private javax.swing.JTextField txtUsernamemendaftarRegisterF;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(AdminModel model) {
        txtUsernamemendaftarRegisterF.setText(model.getUsername());
        txtPasswordmendaftarRegisterF.setText(model.getPassword());
        txtEmailendaftarRegisterF.setText(model.getEmail());
    }

    @Override
    public void onInsert(Admin admin) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onDelete() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onUpdate(Admin admin) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
