/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.arisanuhuy.kocokarisan;

import javax.swing.JFrame;

/**
 *
 * @author faldi
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        
        setExtendedState(JFrame.WIDTH);
        setVisible(true);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrame = new javax.swing.JPanel();
        Logos = new javax.swing.JLabel();
        loginSebagai = new javax.swing.JLabel();
        loginAnggotaButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        loginAdminButton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        backgroundWall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(743, 507));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo.png"))); // NOI18N
        mainFrame.add(Logos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        loginSebagai.setFont(new java.awt.Font("Nexa Light", 0, 24)); // NOI18N
        loginSebagai.setForeground(new java.awt.Color(255, 255, 255));
        loginSebagai.setText("Login Sebagai");
        mainFrame.add(loginSebagai, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 160, 30));

        loginAnggotaButton.setBackground(new java.awt.Color(244, 173, 71));
        loginAnggotaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginAnggotaButtonMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Nexa Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(38, 56, 89));
        jLabel4.setText("Anggota");

        javax.swing.GroupLayout loginAnggotaButtonLayout = new javax.swing.GroupLayout(loginAnggotaButton);
        loginAnggotaButton.setLayout(loginAnggotaButtonLayout);
        loginAnggotaButtonLayout.setHorizontalGroup(
            loginAnggotaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginAnggotaButtonLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        loginAnggotaButtonLayout.setVerticalGroup(
            loginAnggotaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginAnggotaButtonLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        mainFrame.add(loginAnggotaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 170, 80));

        loginAdminButton.setBackground(new java.awt.Color(244, 173, 71));
        loginAdminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginAdminButtonMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Nexa Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 56, 89));
        jLabel5.setText("Admin");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginAdminButtonLayout = new javax.swing.GroupLayout(loginAdminButton);
        loginAdminButton.setLayout(loginAdminButtonLayout);
        loginAdminButtonLayout.setHorizontalGroup(
            loginAdminButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginAdminButtonLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        loginAdminButtonLayout.setVerticalGroup(
            loginAdminButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginAdminButtonLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        mainFrame.add(loginAdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 170, 80));

        backgroundWall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/background.png"))); // NOI18N
        backgroundWall.setToolTipText("");
        mainFrame.add(backgroundWall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        getContentPane().add(mainFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginAnggotaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginAnggotaButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginAnggotaButtonMouseClicked

    private void loginAdminButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginAdminButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginAdminButtonMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logos;
    private javax.swing.JLabel backgroundWall;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel loginAdminButton;
    private javax.swing.JPanel loginAnggotaButton;
    private javax.swing.JLabel loginSebagai;
    private javax.swing.JPanel mainFrame;
    // End of variables declaration//GEN-END:variables
}
